
<div class="header content d-flex ">
   <div class="container-fluid px-0">
        <div class="row">
                <div class="col-md-4 col-sm-6 col-12 d-flex part1">
                    <div class="menu d-flex align-items-center justify-content-center mr-4">
                        <i class='bx bx-menu-alt-right'></i>
                    </div>
                    <div class="logo">
                        MegaMart
                    </div>
                </div>
                <div class="col-md-8 col-sm-6 col-12 part2">
                    <div class="row">
                        <div class="search-bar d-flex align-items-center col-md-6 col-sm-8 col-8">
                            <div class="actions">
                                <i class='bx bx-search-alt-2'></i>
                            </div>
                            <input type="text">
                            <div class="actions">
                                <button>
                                    <i class='bx bx-list-ul'></i>
                                </button>
                            </div>
                        </div>
                        <div class="login col-lg-3 col-md-4 col-sm-2 col-2 d-flex align-items-center justify-content-end">
                            <i class='bx bx-user'></i>
                            <span class="d-none d-md-inline-block">Sign Up/Sign In</span>
                        </div>
                        <div class="carrito col-lg-3 col-md-2 col-sm-2 col-2 d-flex align-items-center justify-content-end">
                            <i class='bx bx-cart-alt'></i>
                            <span class="d-none d-md-inline-block">Cart</span>
                        </div>
                    </div>                    
                </div>
        </div>
    </div>
</div>
