<div class="panel header">
    <div class="container-fluid px-0">
        <div class="row">
            <div class="col-md-5 col-8">
                <div class="welcome">
                    <span>Welcome to worldwide Megamart!</span>
                </div>
            </div>
            <div class="col-md-7 col-4 d-flex justify-content-end">
                <div class="listas pl-2 d-flex align-items-center">
                    <i class='bx bx-map'></i>
                    <span class="d-none d-md-inline-block">Deliver to 423651</span>
                    <span>|</span>

                </div>
                <div class="listas pl-2 d-flex align-items-center">
                    <i class='bx bxs-truck'></i>
                    <span class="d-none d-md-inline-block">Track your order</span>
                    <span>|</span>

                </div>
                <div class="listas pl-2 d-flex align-items-center">
                    <i class='bx bxs-badge-dollar'></i>
                    <span class="d-none d-md-inline-block">All Offers</span>
                    <span></span>
                </div>
            </div>
        </div>
    </div>
</div>
