
 <div class="container-fluid px-0 ">
                <div class="row">
                <div class="col-12 col-sm-12 col-md-4 col-xl-4">
                        <div class="marca mb-5">
                            <span>MegaMart</span>
                        </div>
                        <div class="contacto">
                            <div class="title mb-3">
                                <span>Contact Us</span>
                            </div>
                            <div class="tipo_contacto">
                                <span>Icon</span>
                                <span>Whats App</span>
                                <br>
                                <span>+1 202-918-2132</span>
                            </div>
                            <div class="tipo_contacto">
                                <span>Icon</span>
                                <span>Call Us</span>
                                <br>
                                <span>+1 202-918-2132</span>
                            </div>

                        </div>
                        <div class="app">
                            <div class="title my-3">
                                <span>Download App</span>
                            </div>
                            <div class="img d-flex">
                            <img class="mr-1"src="<?php echo $this->getViewFileUrl('images/footer/AppStore.png') ?>" alt="">
                                <img class="mr-1"src="<?php echo $this->getViewFileUrl('images/footer/AppStore.png') ?>" alt="">
                            </div>
                        </div>

                    </div>
                    <div class="col-12 col-sm-12 col-md-6 col-xl-6">
                        <div class="row">
                            <div class="col-12 col-sm-12 col-xl-6">
                                <div class="link">
                                    <span class="mb-2">Most Popular Categories</span>
                                    <ul>
                                        <li>Staples</li>
                                        <li>Beverages</li>
                                        <li>Personal Care</li>
                                        <li>Home Care</li>
                                        <li>Baby Care</li>
                                        <li>Vegetables & Fruits</li>
                                        <li>Snacks & Foods</li>
                                        <li>Dairy & Bakery</li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-12 col-sm-12 col-xl-6">
                                <div class="link">
                                    <span class="mb-2">Most Popular Categories</span>
                                    <ul>
                                        <li>Staples</li>
                                        <li>Beverages</li>
                                        <li>Personal Care</li>
                                        <li>Home Care</li>
                                        <li>Baby Care</li>
                                        <li>Vegetables & Fruits</li>
                                        <li>Snacks & Foods</li>
                                        <li>Dairy & Bakery</li>
                                    </ul>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="col-0 col-sm-0 col-md-2"></div>
                </div>
                <div class="mask">
            <img src="<?php echo $this->getViewFileUrl('images/footer/mask.svg') ?>" alt="">
        </div>
              </div>
